name: bump version & publish to npm

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore')"
    steps:
      - uses: actions/checkout@v2

      - name: install node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "npm"

      - run: npm install --no-save

      - name: build package
        run: npm run build

      - name: bump version and create tag
        uses: "phips28/gh-action-bump-version@master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          minor-wording: "feat,feature"
          major-wording: "major"

      - name: publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
